[package]
name = "rust-programming-mastery"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "3"
members = [
    "section-01-structs/*", 
    "section-02-file-systems/*"
]

[workspace.dependencies]
